[providers]
php = "8.0"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_FALLBACK_PATH = "/app/public/index.php"

[phases.build]
cmds = [
    "mkdir -p storage/logs",
    "mkdir -p storage/framework/cache",
    "mkdir -p storage/framework/sessions", 
    "mkdir -p storage/framework/views",
    "chmod -R 775 storage",
    "chmod -R 775 bootstrap/cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
